### PR TITLE
Generated by robot

### PR DESCRIPTION
**Pull request by caesarxuchao**
All 5 PRs generated in the same run of the robot:
https://github.com/kubernetes/client-go/pull/140
https://github.com/kubernetes/apimachinery/pull/10
https://github.com/kubernetes/apiserver/pull/4
https://github.com/kubernetes/kube-aggregator/pull/4
https://github.com/kubernetes/sample-apiserver/pull/2

### CODE REVIEW

**Comment by sttts** [comment]
Same here: a real `vendor/` dir **including** `k8s.io/*` should exist.

**Comment by deads2k** [comment]
> Same here: a real vendor/ dir including k8s.io/* should exist.

It would be nice, but being able to auto-sync is so helpful, I'd take it without.

lgtm

**Comment by deads2k** [comment]
> Do you provide any helper scripts in the repos for now to restore the state to something usable once downloaded?

In theory there's nothing special needed.  godep restore should just work.

**Comment by deads2k** [comment]
merging in preparation for turning on the auto-sync scripts

**Pull request merged**
