### PR TITLE
ValidatingAdmissionWebhook issue demonstration

### PR DESCRIPTION
**Pull request by ychen-atlassian**
Steps:

1. Start up sample-apiserver with the provided rc.yaml. yiyangc91/kube-sample-apiserver:latest points to the a build of sample-apiserver but you are free to build your own in case you don't want to spawn random docker images
2. Create the `artifacts/example/webhookconfig.yaml`. This doesn't reference any real webhook but the failPolicy is set to "Fail", so no "Flunders" should be able to be created.
3. Create a flunder by running `kubectl create -f artifacts/flunders/01-flunder.yaml`

Without installing the admissioninstall packages in `pkg/apiserver/apiserver.go` (try to remove it), when we try to use ValidatingAdmissionWebhook, we get this error:

```
Error from server (InternalError): error when creating "artifacts/flunders/01-flunder.yaml": Internal error occurred: failed calling admission webhook "warbles.k8s.io": no kind is registered for the type v1beta1.AdmissionReview
```

After installing we get a better message:

```
Error from server (InternalError): error when creating "artifacts/flunders/01-flunder.yaml": Internal error occurred: failed calling admission webhook "warbles.k8s.io": Post https://192.168.64.1:8080/externalid: dial tcp 192.168.64.1:8080: getsockopt: connection refused
```

(This is the failPolicy taking effect)

This issue seems to be specific to the ValidatingAdmissionWebhook and the MutatingAdmissionWebhook. All other admission controllers probably work?

Docker images:

- yiyangc91/kube-sample-apiserver (sha256:70a1bb48ec3b2d275e1405f3530d0a91bb161e7f1c91aa88eb241cc5fb87eaf3) - the working version
- yiyangc91/kube-sample-apiserver:broken (sha256:7d955e2db6177f66f5d8d5e04a2b3de4d04e47d3230e83e3a4b5f5b547eb67d3) - the broken version

### CODE REVIEW

**Comment by erictune** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by deads2k** [comment]
Is this fixed by @sttts's pull here: https://github.com/kubernetes/kubernetes/pull/60965 ?

Looks like it would fix the registration and then you get the failure you expect, rigth?

**Comment by sttts** [comment]
@deads2k looks like the same error, yes.

**Comment by deads2k** [comment]
/hold

just so no one merges this. It was a good demonstration.

**Comment by sttts** [comment]
@ychen-atlassian can you confirm that my PR fixes the issue?

**Comment by ychen-atlassian** [comment]
Hi @sttts 

Thanks for the quick fix! I've manually applied the patch to the vendor directory and confirmed that it hits the "connection refused" message, indicating that the scheme has the types registered now.

**Pull request closed without merging**
